#!/usr/bin/env python3

# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 PHYTEC Messtechnik GmbH
# Author: Martin Schwan <m.schwan@phytec.de>

if __name__ == '__main__':
    from demo_celebrity_face_match import aidemo

    aidemo.main()
